# -*- coding: utf-8 -*-
"""RGB canales1-2-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LtSu5xtIhmfIJRaUXIY7rxDKA7XkhCp9
"""

import pylab as plt
import numpy as np
from netCDF4 import Dataset

"""**Hora 19:30 UTC-13:30 Hora en Costa Rica** producto: **Radiances**

Banda 1
"""

!wget https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadF/2020/262/19/OR_ABI-L1b-RadF-M6C01_G16_s20202621930205_e20202621939513_c20202621939571.nc

"""Banda 2"""

!wget https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadF/2020/262/19/OR_ABI-L1b-RadF-M6C02_G16_s20202621930205_e20202621939513_c20202621939561.nc

"""Banda 3

"""

!wget https://noaa-goes16.s3.amazonaws.com/ABI-L1b-RadF/2020/262/19/OR_ABI-L1b-RadF-M6C03_G16_s20202621930205_e20202621939513_c20202621939577.nc

CH1= Dataset('OR_ABI-L1b-RadF-M6C01_G16_s20202621930205_e20202621939513_c20202621939571.nc')
CH2 = Dataset('OR_ABI-L1b-RadF-M6C02_G16_s20202621930205_e20202621939513_c20202621939561.nc')
CH3= Dataset('OR_ABI-L1b-RadF-M6C03_G16_s20202621930205_e20202621939513_c20202621939577.nc')

CH1

np.shape(CH1.variables['Rad'][:])

np.shape(CH2.variables['Rad'][:])

np.shape(CH3.variables['Rad'][:])

BLUE = CH1.variables['Rad'][:][::2,::2]
GREEN =CH3.variables['Rad'][:][::2,::2]
RED=CH2.variables['Rad'][:][::4,::4]

RED=(RED-RED.min())/(RED.max()-RED.min())
GREEN=(GREEN-GREEN.min())/(GREEN.max()-GREEN.min())
BLUE=(BLUE-BLUE.min())/(BLUE.max()-BLUE.min())

np.shape(RED)

np.shape(GREEN)

np.shape(BLUE)

COLORES=np.zeros((5424, 5424,3))

COLORES[:,:,0]=RED

COLORES[:,:,1]=GREEN

COLORES[:,:,2]=BLUE

plt.figure(figsize = (5,5),dpi=150)
plt.imshow(COLORES)

plt.figure(figsize = (5,5),dpi=150)
plt.xlim(2000,2500)
plt.ylim(2300,2000)
plt.title('RGB con canales 1-2-3 a las 19:30 UTC con el producto "raciances"')
plt.imshow(COLORES)

plt.figure(figsize = (5,5),dpi=150)
plt.xlim(2200,2300)
plt.ylim(2300,2200)
plt.title('RGB con canales 1-2-3 a las 19:30 UTC con el producto "raciances"')
plt.imshow(COLORES)